/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package apresentacao;

import javax.swing.JFileChooser;
import javax.swing.ImageIcon;
import java.awt.Image;
import javax.swing.JOptionPane;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.ButtonGroup;
import negocio.Aluno;
import persistencia.AlunoDAO;
import persistencia.IAlunoDAO;

/**
 *
 * @author giuli
 */
public class fmAluno extends javax.swing.JInternalFrame {
    // Variável global da tela para guardar o caminho da foto
    String caminhoFoto = "";
    private ButtonGroup grupoSexo;
    /**
     * Creates new form fmAluno
     */
    public fmAluno() {
        initComponents();
        configurarRadioButtons();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jDesktopPane = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCPF = new javax.swing.JFormattedTextField();
        txtTelefone = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        rbMasculino = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        cbPlano = new javax.swing.JComboBox<>();
        btUpload = new javax.swing.JButton();
        btNovo = new javax.swing.JButton();
        btSalvar = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtEndereco = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtDataNascimento = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        rbFeminino = new javax.swing.JRadioButton();
        rbOutro = new javax.swing.JRadioButton();
        laDataMatricula = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lbFoto = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Cadastro de Alunos");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jDesktopPane.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Insira os Dados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 153, 153))); // NOI18N

        jLabel1.setText("Nome :");

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        jLabel2.setText("CPF :");

        jLabel3.setText("Telefone :");

        try {
            txtCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txtTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel4.setText("Sexo");

        rbMasculino.setText("Masculino");
        rbMasculino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMasculinoActionPerformed(evt);
            }
        });

        jLabel5.setText("Plano :");

        cbPlano.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mensal", "Trimestral", "Semestral", "Anual" }));
        cbPlano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPlanoActionPerformed(evt);
            }
        });

        btUpload.setForeground(new java.awt.Color(255, 255, 255));
        btUpload.setText("Carregar Foto");
        btUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUploadActionPerformed(evt);
            }
        });

        btNovo.setBackground(new java.awt.Color(0, 153, 51));
        btNovo.setForeground(new java.awt.Color(255, 255, 255));
        btNovo.setText("Novo");
        btNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoActionPerformed(evt);
            }
        });

        btSalvar.setBackground(new java.awt.Color(102, 102, 255));
        btSalvar.setForeground(new java.awt.Color(255, 255, 255));
        btSalvar.setText("Salvar");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        jLabel6.setText("Endereço :");

        txtEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnderecoActionPerformed(evt);
            }
        });

        jLabel7.setText("Data de nascimento :");

        try {
            txtDataNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel8.setText("Email :");

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        rbFeminino.setText("Feminino");

        rbOutro.setText("Outro");

        laDataMatricula.setText("##/##/####");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbFoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbFoto, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
        );

        jDesktopPane.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane.setLayer(txtNome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane.setLayer(txtCPF, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane.setLayer(txtTelefone, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane.setLayer(rbMasculino, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane.setLayer(cbPlano, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane.setLayer(btUpload, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane.setLayer(btNovo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane.setLayer(btSalvar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane.setLayer(btCancelar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane.setLayer(txtEndereco, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane.setLayer(txtDataNascimento, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane.setLayer(txtEmail, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane.setLayer(rbFeminino, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane.setLayer(rbOutro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane.setLayer(laDataMatricula, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPaneLayout = new javax.swing.GroupLayout(jDesktopPane);
        jDesktopPane.setLayout(jDesktopPaneLayout);
        jDesktopPaneLayout.setHorizontalGroup(
            jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPaneLayout.createSequentialGroup()
                        .addGroup(jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel8)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPaneLayout.createSequentialGroup()
                                .addGroup(jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtTelefone)
                                    .addComponent(txtCPF)
                                    .addComponent(txtNome, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                                    .addComponent(txtDataNascimento)
                                    .addComponent(txtEmail))
                                .addGroup(jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jDesktopPaneLayout.createSequentialGroup()
                                        .addGap(43, 43, 43)
                                        .addComponent(laDataMatricula)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jDesktopPaneLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btUpload, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                            .addGroup(jDesktopPaneLayout.createSequentialGroup()
                                .addComponent(cbPlano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPaneLayout.createSequentialGroup()
                        .addGroup(jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPaneLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbFeminino)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbMasculino)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbOutro))
                            .addGroup(jDesktopPaneLayout.createSequentialGroup()
                                .addComponent(btNovo)
                                .addGap(18, 18, 18)
                                .addComponent(btSalvar)
                                .addGap(18, 18, 18)
                                .addComponent(btCancelar))
                            .addGroup(jDesktopPaneLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(44, 44, 44)))
                .addContainerGap())
        );
        jDesktopPaneLayout.setVerticalGroup(
            jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(laDataMatricula, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPaneLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btUpload, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDesktopPaneLayout.createSequentialGroup()
                        .addGroup(jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbPlano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(rbFeminino)
                    .addComponent(rbMasculino)
                    .addComponent(rbOutro))
                .addGap(18, 18, 18)
                .addGroup(jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCancelar)
                    .addComponent(btSalvar)
                    .addComponent(btNovo))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    File arquivoFoto = null;
    private String caminhoFotoPadrao = "C:/Users/Administrator/Documents/FotosAlunos/";
    
    private void copiarArquivo(File origem, File destino) throws IOException {
        OutputStream out;
        try (InputStream in = new FileInputStream(origem)) {
            out = new FileOutputStream(destino);
            byte[] buf = new byte[1024];
            int len;
            while ((len = in.read(buf)) > 0) {
                out.write(buf, 0, len);
            }
        }
        out.close();
    }

    private void habilitarCampos(boolean entrada) {
        txtNome.setEnabled(entrada);
        txtCPF.setEnabled(entrada);
        txtTelefone.setEnabled(entrada);
        txtDataNascimento.setEnabled(entrada);
        txtEmail.setEnabled(entrada);
        cbPlano.setEnabled(entrada);
        txtEndereco.setEnabled(entrada);
        rbMasculino.setEnabled(entrada);
        rbFeminino.setEnabled(entrada);
        rbOutro.setEnabled(entrada);
        btUpload.setEnabled(entrada);
    }

    
    private void btUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUploadActionPerformed
        JFileChooser arquivo = new JFileChooser();
        arquivo.setDialogTitle("Selecione uma foto");
        arquivo.setFileSelectionMode(JFileChooser.FILES_ONLY);

        // Filtro para imagens
        arquivo.setFileFilter(new javax.swing.filechooser.FileFilter() {
            @Override
            public boolean accept(File f) {
                if (f.isDirectory()) return true;
                String nome = f.getName().toLowerCase();
                return nome.endsWith(".jpg") || nome.endsWith(".jpeg") || 
                       nome.endsWith(".png") || nome.endsWith(".gif");
            }

            @Override
            public String getDescription() {
                return "Imagens (*.jpg, *.jpeg, *.png, *.gif)";
            }
        });

        int opc = arquivo.showOpenDialog(this);

        if (opc == JFileChooser.APPROVE_OPTION) {
            arquivoFoto = arquivo.getSelectedFile();

            // Redimensionar e mostrar
            ImageIcon imagem = new ImageIcon(arquivoFoto.getPath());
            int largura = lbFoto.getWidth();
            int altura = lbFoto.getHeight();

            if (largura <= 0 || altura <= 0) {
                largura = 150;
                altura = 150;
            }

            Image imgRedimensionada = imagem.getImage().getScaledInstance(
                largura, altura, Image.SCALE_SMOOTH);

            ImageIcon iconeFinal = new ImageIcon(imgRedimensionada);
            lbFoto.setIcon(iconeFinal);

            JOptionPane.showMessageDialog(this, 
                "Foto carregada: " + arquivoFoto.getName(), 
                "Sucesso", 
                JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btUploadActionPerformed

    private void btNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btNovoActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        // 1. VERIFICAÇÃO DE CAMPOS OBRIGATÓRIOS
        String nome = txtNome.getText().trim();
        String cpf = txtCPF.getText().trim().replaceAll("[^0-9]", "");
        String telefone = txtTelefone.getText().trim();
        String dataNasc = txtDataNascimento.getText().trim();
        String email = txtEmail.getText().trim();
        String endereco = txtEndereco.getText().trim();

        // Validações básicas
        if (nome.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Informe o nome!", "Aviso", JOptionPane.WARNING_MESSAGE);
            txtNome.requestFocus();
            return;
        }
        
        if (cpf.length() != 11) {
            JOptionPane.showMessageDialog(this, "CPF inválido! (11 dígitos)", "Aviso", JOptionPane.WARNING_MESSAGE);
            txtCPF.requestFocus();
            return;
        }
        
        if (!telefoneValido(telefone)) {
            JOptionPane.showMessageDialog(this, 
                "Telefone inválido!\nUse o formato: (##) #####-####", 
                "Aviso", 
                JOptionPane.WARNING_MESSAGE);
            txtTelefone.requestFocus();
            return;
        }
        
        if (dataNasc.length() != 10 || !dataNasc.matches("\\d{2}/\\d{2}/\\d{4}")) {
            JOptionPane.showMessageDialog(this, 
                "Formato de data inválido!\nUse: dd/mm/aaaa", 
                "Aviso", 
                JOptionPane.WARNING_MESSAGE);
            txtDataNascimento.requestFocus();
            return;
        }

        // 2. VALIDAÇÃO DA DATA DE NASCIMENTO COM SUAS FUNÇÕES


        try {
            // Extrair dia, mês e ano da string
            String[] partes = dataNasc.split("/");
            int dia = Integer.parseInt(partes[0]);
            int mes = Integer.parseInt(partes[1]);
            int ano = Integer.parseInt(partes[2]);

            // Usar suas funções de validação
            if (!dataNascimentoValida(dia, mes, ano)) {
                JOptionPane.showMessageDialog(this, 
                    "Data de nascimento inválida!\n" +
                    "Verifique se:\n" +
                    "- Dia está entre 1-31\n" +
                    "- Mês está entre 1-12\n" +
                    "- Ano entre 1900-2025\n" +
                    "- Dia compatível com o mês", 
                    "Data inválida", 
                    JOptionPane.WARNING_MESSAGE);
                txtDataNascimento.requestFocus();
                return;
            }

            // Verificar se é data futura (não pode nascer no futuro)
            Calendar dataNascCal = Calendar.getInstance();
            dataNascCal.set(ano, mes-1, dia); // mês-1 porque Calendar.JANUARY = 0
            Calendar hoje = Calendar.getInstance();

            if (dataNascCal.after(hoje)) {
                JOptionPane.showMessageDialog(this, 
                    "Data de nascimento não pode ser no futuro!", 
                    "Data inválida", 
                    JOptionPane.WARNING_MESSAGE);
                txtDataNascimento.requestFocus();
                return;
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, 
                "Data contém valores não numéricos!", 
                "Erro", 
                JOptionPane.ERROR_MESSAGE);
            txtDataNascimento.requestFocus();
            return;
        }
        
        if (!emailValido(email)) {
            JOptionPane.showMessageDialog(this, "Email inválido!", "Aviso", JOptionPane.WARNING_MESSAGE);
            txtEmail.requestFocus();
            return;
        }
        
        if (endereco.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Informe o endereço", "Aviso", JOptionPane.WARNING_MESSAGE);
            txtNome.requestFocus();
            return;
        }


        if (!rbMasculino.isSelected() && !rbFeminino.isSelected() && !rbOutro.isSelected()) {
            JOptionPane.showMessageDialog(this, "Selecione o sexo!", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }


        
        if (!fotoValida(arquivoFoto)) {
            JOptionPane.showMessageDialog(this, 
                "Selecione uma foto para o aluno!", 
                "Foto obrigatória", 
                JOptionPane.WARNING_MESSAGE);
            btUpload.requestFocus();
            return;
        }
        
        int confirmacao = JOptionPane.showConfirmDialog(this, 
            "Deseja salvar este aluno?", 
            "Confirmar", 
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE);

        if (confirmacao != JOptionPane.YES_OPTION) {
            return;
        }
        
        try {
            // 6. CRIAR OBJETO ALUNO
            Aluno aluno = new Aluno();
            aluno.setNome(nome);
            aluno.setCpf(cpf);
            aluno.setTelefone(telefone);
            aluno.setEmail(email);
            aluno.setEndereco(endereco);
            aluno.setPlano(cbPlano.getSelectedItem().toString());

            // Sexo
            if (rbMasculino.isSelected()) {
                aluno.setSexo("M");
            } else if (rbFeminino.isSelected()) {
                aluno.setSexo("F");
            } else {
                aluno.setSexo("O");
            }

            aluno.setAtivo(true);

            // Data de Nascimento (já validada acima)
            String[] partes = dataNasc.split("/");
            int dia = Integer.parseInt(partes[0]);
            int mes = Integer.parseInt(partes[1]);
            int ano = Integer.parseInt(partes[2]);

            Calendar dataNascCal = Calendar.getInstance();
            dataNascCal.set(ano, mes-1, dia);
            aluno.setDataNascimento(dataNascCal.getTime());

            // Data de Matrícula (data atual)
            Calendar dataMatCal = Calendar.getInstance();
            dataMatCal.setTime(new java.util.Date());
            aluno.setDataMatricula(dataMatCal.getTime());

            // 7. TRATAMENTO DA FOTO
            String caminhoFotoFinal = "";
            if (arquivoFoto != null && arquivoFoto.exists()) {
                File pastaFotos = new File(caminhoFotoPadrao);
                if (!pastaFotos.exists()) {
                    pastaFotos.mkdirs();
                }

                String nomeArquivo = nome.replaceAll(" ", "_") + "_" + System.currentTimeMillis() + ".jpg";
                File destinoFoto = new File(caminhoFotoPadrao + nomeArquivo);
                copiarArquivo(arquivoFoto, destinoFoto);
                caminhoFotoFinal = destinoFoto.getAbsolutePath();
            }
            aluno.setFoto(caminhoFotoFinal);

            // 8. SALVAR NO BANCO
            IAlunoDAO alunoDAO = new AlunoDAO();
            alunoDAO.adiciona(aluno);

            // 9. MENSAGEM DE SUCESSO
            JOptionPane.showMessageDialog(this, 
                "Aluno cadastrado com sucesso!\n" +
                "Nome: " + aluno.getNome() + "\n" +
                "CPF: " + aluno.getCpf() + "\n" +
                "Data Nasc: " + dataNasc, 
                "Sucesso", 
                JOptionPane.INFORMATION_MESSAGE);

            // 10. LIMPAR CAMPOS E DESABILITAR
            limpar();
            habilitarCampos(false);

        } catch (Exception e) {
            // 11. TRATAMENTO DE ERRO
            JOptionPane.showMessageDialog(this, 
                "Erro ao salvar aluno: " + e.getMessage(), 
                "Erro", 
                JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_btSalvarActionPerformed

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        // TODO add your handling code here:
        limpar();
        this.dispose();
    }//GEN-LAST:event_btCancelarActionPerformed

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        // TODO add your handling code here:
        //definindo data de matricula como data atual
        DateFormat data = new SimpleDateFormat("dd/MM/yyyy");
        Date dataAtual = new Date();
        laDataMatricula.setText(data.format(dataAtual));       
    }//GEN-LAST:event_formInternalFrameActivated

    private void rbMasculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMasculinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbMasculinoActionPerformed

    private void cbPlanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPlanoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbPlanoActionPerformed

    private void txtEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEnderecoActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed
    private void configurarRadioButtons() {
        // Cria o ButtonGroup
        grupoSexo = new ButtonGroup();
        
        // Adiciona os RadioButtons ao grupo
        grupoSexo.add(rbMasculino);
        grupoSexo.add(rbFeminino);
        grupoSexo.add(rbOutro);
    }
    
    private void limpar() {
        txtNome.setText("");
        txtCPF.setText("");
        txtTelefone.setText("");
        txtDataNascimento.setText("");
        txtEmail.setText("");
        cbPlano.setSelectedIndex(0);
        lbFoto.setIcon(null);
        caminhoFoto = "";
        txtEndereco.setText("");
        grupoSexo.clearSelection();
    }
    
    public static boolean emailValido(String email) {
        if (email == null || email.isEmpty()) {
            return false;
        }

        // Regex simples e prÃ¡tica para verificar formato de e-mail
        String regex = "^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+$";

        return email.matches(regex);
    }
        
    public static boolean anoValido(int ano) {
        return ano >= 1900 && ano <= 2025;
    }

    public static boolean mesValido(int mes) {
        return mes >= 1 && mes <= 12;
    }

    public static boolean diaValido(int dia, int mes) {
        if (!mesValido(mes)) {
            return false;
        }

        if (dia < 1 || dia > 31) { // você falou 0 a 31, mas normalmente dia começa em 1
            return false;
        }

        switch (mes) {
            // meses com 31 dias
            case 1: case 3: case 5: case 7: case 8: case 10: case 12:
                return dia <= 31;

            // meses com 30 dias
            case 4: case 6: case 9: case 11:
                return dia <= 30;

            // fevereiro
            case 2:
                return dia <= 28;

            default:
                return false; // nunca deveria chegar aqui por causa do mesValido
        }
    }

    public static boolean dataNascimentoValida(int dia, int mes, int ano) {
        if (!anoValido(ano)) {
            return false;
        }

        if (!mesValido(mes)) {
            return false;
        }

        if (!diaValido(dia, mes)) {
            return false;
        }

        return true;
    }
    public static boolean telefoneValido(String telefone) {
        if (telefone == null) {
            return false;
        }

        // remove tudo que não for dígito
        String digitos = telefone.replaceAll("\\D", "");

        // Com a máscara (##) #####-####, o correto são 11 dígitos
        return digitos.length() == 11;
    }
    
    public static boolean fotoValida(File arquivoFoto) {
        // Foto obrigatória: precisa ter sido selecionada e existir
        if (arquivoFoto == null) {
            return false;
        }
        return arquivoFoto.exists() && arquivoFoto.isFile();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btNovo;
    private javax.swing.JButton btSalvar;
    private javax.swing.JButton btUpload;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbPlano;
    private javax.swing.JDesktopPane jDesktopPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel laDataMatricula;
    private javax.swing.JLabel lbFoto;
    private javax.swing.JRadioButton rbFeminino;
    private javax.swing.JRadioButton rbMasculino;
    private javax.swing.JRadioButton rbOutro;
    private javax.swing.JFormattedTextField txtCPF;
    private javax.swing.JFormattedTextField txtDataNascimento;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtNome;
    private javax.swing.JFormattedTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}
