/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package apresentacao;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import negocio.Aluno;
import negocio.AvaliacaoFisica;
import negocio.Funcionario;
import persistencia.AlunoDAO;
import persistencia.AvaliacaoFisicaDAO;
import persistencia.FuncionarioDAO;
import persistencia.IAlunoDAO;
import persistencia.IAvaliacaoFisicaDAO;
import persistencia.IFuncionarioDAO;

/**
 *
 * @author giuli
 */
public class fmAvaliacao extends javax.swing.JInternalFrame {

    /**
     * Creates new form fmAvaliacao
     */
    public fmAvaliacao() {
        initComponents();
        // Simulando dados do Banco de Dados
    cbAluno.removeAllItems(); // Limpa sujeira
    cbAluno.addItem("Selecione um aluno...");
    cbAluno.addItem("João da Silva");
    cbAluno.addItem("Maria Oliveira");
    cbAluno.addItem("Pedro Santos");

    cbFuncionario.removeAllItems();
    cbFuncionario.addItem("Instrutor Padrão");
    cbFuncionario.addItem("Personal Trainer X");
    this.setSize(700, 600);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbAluno = new javax.swing.JComboBox<>();
        cbFuncionario = new javax.swing.JComboBox<>();
        laData = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtPeso = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtAltura = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtGordura = new javax.swing.JTextField();
        btCalcularIMC = new javax.swing.JButton();
        lblResultadoIMC = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtObservacoes = new javax.swing.JTextArea();
        btSalvar = new javax.swing.JButton();
        btSair = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 0, 204));
        setClosable(true);
        setTitle("Nota Avaliação Física");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Identificação", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 153, 153))); // NOI18N

        jLabel1.setText("Aluno");

        jLabel2.setText("Instrutor");

        cbAluno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbFuncionario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        laData.setText("##/##/####");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(cbAluno, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(laData)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(cbAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(laData))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Medidas Corporais"));

        jLabel3.setText("Peso (kg)");

        txtPeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesoActionPerformed(evt);
            }
        });

        jLabel4.setText("Altura (m)");

        txtAltura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlturaActionPerformed(evt);
            }
        });

        jLabel5.setText("%Gordura");

        btCalcularIMC.setText("Calcular IMC");
        btCalcularIMC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCalcularIMCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtGordura, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(104, 104, 104))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAltura)
                            .addComponent(txtPeso))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btCalcularIMC)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblResultadoIMC)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btCalcularIMC)
                    .addComponent(lblResultadoIMC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtGordura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtObservacoes.setColumns(20);
        txtObservacoes.setRows(5);
        jScrollPane1.setViewportView(txtObservacoes);

        btSalvar.setBackground(new java.awt.Color(0, 153, 51));
        btSalvar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btSalvar.setForeground(new java.awt.Color(255, 255, 255));
        btSalvar.setText("Salvar");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(btSalvar)
                        .addGap(31, 31, 31)
                        .addComponent(btSair)))
                .addGap(8, 8, 8))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSalvar)
                    .addComponent(btSair))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesoActionPerformed

    private void txtAlturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlturaActionPerformed

    private void btCalcularIMCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCalcularIMCActionPerformed
       try {
        // 1. Pegar o texto e trocar vírgula por ponto (pra não dar erro se digitar 1,75)
        String strPeso = txtPeso.getText().replace(",", ".");
        String strAltura = txtAltura.getText().replace(",", ".");
        
        // 2. Converter para números (double)
        double peso = Double.parseDouble(strPeso);
        double altura = Double.parseDouble(strAltura);
        
        // 3. A Fórmula Mágica: Peso dividido por (Altura vezes Altura)
        double imc = peso / (altura * altura);
        
        // 4. Formatar para mostrar só 2 casas decimais (ex: 24.50)
        String resultadoFormatado = String.format("%.2f", imc);
        
        // 5. Mostrar no Label
        // Verifica o status só pra ficar bonito
        String status = "";
        if (imc < 18.5) status = " (Abaixo do Peso)";
        else if (imc < 25) status = " (Peso Normal)";
        else if (imc < 30) status = " (Sobrepeso)";
        else status = " (Obesidade)";
        
        lblResultadoIMC.setText("IMC: " + resultadoFormatado + status);
        
    } catch (NumberFormatException e) {
        // Se a pessoa digitar letras ou deixar vazio
        javax.swing.JOptionPane.showMessageDialog(this, "Por favor, digite números válidos no Peso e Altura!");
    } 
    }//GEN-LAST:event_btCalcularIMCActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        try {
            // 1. VALIDAÇÃO BÁSICA
            if (cbAluno.getSelectedIndex() == 0) {
                JOptionPane.showMessageDialog(this, "Selecione um aluno!", "Aviso", JOptionPane.WARNING_MESSAGE);
                return;
            }

            if (cbFuncionario.getSelectedIndex() == 0) {
                JOptionPane.showMessageDialog(this, "Selecione um instrutor!", "Aviso", JOptionPane.WARNING_MESSAGE);
                return;
            }

            // 2. PEGAR VALORES
            String strPeso = txtPeso.getText().trim().replace(",", ".");
            String strAltura = txtAltura.getText().trim().replace(",", ".");
            String strGordura = txtGordura.getText().trim().replace(",", ".");
            String observacoes = txtObservacoes.getText().trim();

            // 3. CONVERTER E VALIDAR LIMITES
            double peso, altura, gordura = 0;

            try {
                // Peso: 0.1 a 300 kg
                peso = Double.parseDouble(strPeso);
                if (peso < 0.1 || peso > 300) {
                    JOptionPane.showMessageDialog(this, 
                        "Peso inválido! (0.1 a 300 kg)", 
                        "Valor fora do limite", 
                        JOptionPane.WARNING_MESSAGE);
                    txtPeso.requestFocus();
                    return;
                }
                
                // Altura: 0.5 a 3.0 metros
                altura = Double.parseDouble(strAltura);
                if (altura < 0.5 || altura > 3.0) {
                    JOptionPane.showMessageDialog(this, 
                        "Altura inválida! (0.5 a 3.0 metros)", 
                        "Valor fora do limite", 
                        JOptionPane.WARNING_MESSAGE);
                    txtAltura.requestFocus();
                    return;
                }
                
                // Gordura: 0 a 100% (opcional)
                if (!strGordura.isEmpty()) {
                    gordura = Double.parseDouble(strGordura);
                    if (gordura < 0 || gordura > 100) {
                        JOptionPane.showMessageDialog(this, 
                            "Gordura corporal inválida! (0 a 100%)", 
                            "Valor fora do limite", 
                            JOptionPane.WARNING_MESSAGE);
                        txtGordura.requestFocus();
                        return;
                    }
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, 
                    "Digite apenas números nos campos!\n" +
                    "Use ponto ou vírgula para decimais.\n" +
                    "Ex: 70.5 ou 70,5", 
                    "Formato inválido", 
                    JOptionPane.ERROR_MESSAGE);
                return;
            }

            // 4. EXTRAIR IDs
            int idAluno = extrairIdDoCombo(cbAluno);
            int idInstrutor = extrairIdDoCombo(cbFuncionario);

            if (idAluno <= 0 || idInstrutor <= 0) {
                JOptionPane.showMessageDialog(this, 
                    "IDs inválidos!\nAluno: " + idAluno + "\nInstrutor: " + idInstrutor, 
                    "Erro", 
                    JOptionPane.ERROR_MESSAGE);
                return;
            }

            // 5. CONFIRMAÇÃO
            int confirm = JOptionPane.showConfirmDialog(this, 
                "Salvar avaliação física?\n\n" +
                "Aluno ID: " + idAluno + "\n" +
                "Instrutor ID: " + idInstrutor + "\n" +
                "Peso: " + peso + " kg\n" +
                "Altura: " + altura + " m", 
                "Confirmar", 
                JOptionPane.YES_NO_OPTION);

            if (confirm != JOptionPane.YES_OPTION) {
                return;
            }

            // 6. CRIAR OBJETO
            negocio.AvaliacaoFisica avaliacao = new negocio.AvaliacaoFisica();
            avaliacao.setPeso(peso);
            avaliacao.setAltura(altura);
            avaliacao.setGorduraCorporal(gordura);
            avaliacao.setObservacoes(observacoes);
            avaliacao.setDataAvaliacao(new java.util.Date());
            avaliacao.setIdAluno(idAluno);
            avaliacao.setIdInstrutor(idInstrutor);

            // 7. SALVAR NO BANCO
            IAvaliacaoFisicaDAO dao = new AvaliacaoFisicaDAO();
            dao.adiciona(avaliacao);

            // 8. MENSAGEM DE SUCESSO
            JOptionPane.showMessageDialog(this, 
                "✅ Avaliação salva com sucesso!\n\n" +
                "📋 Resumo:\n" +
                "• Aluno ID: " + idAluno + "\n" +
                "• Instrutor ID: " + idInstrutor + "\n" +
                "• Peso: " + String.format("%.1f", peso) + " kg\n" +
                "• Altura: " + String.format("%.2f", altura) + " m\n" +
                "• Gordura: " + (gordura > 0 ? String.format("%.1f", gordura) + "%" : "Não informado") + "\n" +
                "• Data: " + new SimpleDateFormat("dd/MM/yyyy").format(new java.util.Date()), 
                "Sucesso", 
                JOptionPane.INFORMATION_MESSAGE);

            // 9. LIMPAR CAMPOS
            limparCampos();

        } catch (Exception e) {
            // TRATAMENTO ESPECÍFICO PARA "OUT OF RANGE"
            String mensagemErro = "❌ Erro ao salvar!\n";
            
            if (e.getMessage() != null) {
                if (e.getMessage().contains("out of range") || 
                    e.getMessage().contains("Data truncation") ||
                    e.getMessage().contains("value too large")) {
                    mensagemErro += "\n👉 VALOR FORA DOS LIMITES PERMITIDOS!\n\n" +
                                  "Limites do banco:\n" +
                                  "• Peso: até 999.99 kg\n" +
                                  "• Altura: até 9.99 metros\n" +
                                  "• Gordura: até 100%\n\n" +
                                  "Ajuste os valores e tente novamente.";
                } else if (e.getMessage().contains("foreign key constraint")) {
                    mensagemErro += "\n👉 ALUNO OU INSTRUTOR NÃO EXISTE!\n\n" +
                                  "Verifique se os IDs selecionados existem no banco.";
                } else {
                    mensagemErro += "\nDetalhe: " + e.getMessage();
                }
            }
            
            JOptionPane.showMessageDialog(this, 
                mensagemErro, 
                "Erro", 
                JOptionPane.ERROR_MESSAGE);
            
            // Log para debug
            System.err.println("ERRO AO SALVAR AVALIAÇÃO:");
            e.printStackTrace();
        }
    }//GEN-LAST:event_btSalvarActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btSairActionPerformed

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        // TODO add your handling code here:
        DateFormat data = new SimpleDateFormat("dd/MM/yyyy");
        Date dataAtual = new Date();
        laData.setText(data.format(dataAtual));    
        try {
            // ALUNOS
            IAlunoDAO alunoDAO = new AlunoDAO();
            DefaultComboBoxModel modeloAluno = new DefaultComboBoxModel();

            // Adiciona opção padrão
            modeloAluno.addElement("Id Aluno    ");

            for (Aluno aluno : alunoDAO.listarTodos()) {
                modeloAluno.addElement(aluno.getIdAluno());
            }

            cbAluno.setModel(modeloAluno);
            cbAluno.setSelectedIndex(0); // Seleciona a primeira opção

            IFuncionarioDAO funcionarioDAO = new FuncionarioDAO();
            DefaultComboBoxModel modeloFunc = new DefaultComboBoxModel();

            modeloFunc.addElement("Id Funcionario");

            for (Funcionario func : funcionarioDAO.listarTodos()) {
                modeloFunc.addElement(func.getIdFuncionario());
            }

            cbFuncionario.setModel(modeloFunc);
            cbFuncionario.setSelectedIndex(0);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, 
                "Erro ao carregar dados: " + e.getMessage(), 
                "Erro", 
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_formInternalFrameActivated
    private int extrairIdDoCombo(javax.swing.JComboBox<String> combo) {
        Object itemSelecionado = combo.getSelectedItem();
        if (itemSelecionado == null) {
            return 0;
        }

        String texto = itemSelecionado.toString().trim();

        // Se o combo mostra apenas o ID
        try {
            return Integer.parseInt(texto);
        } catch (NumberFormatException e) {
            // Se o combo mostra "ID - Nome", extrai o ID
            if (texto.contains("-")) {
                try {
                    String[] partes = texto.split("-");
                    return Integer.parseInt(partes[0].trim());
                } catch (Exception ex) {
                    return 0;
                }
            }
            return 0;
        }
    }

    private void limparCampos() {
        txtPeso.setText("");
        txtAltura.setText("");
        txtGordura.setText("");
        txtObservacoes.setText("");
        lblResultadoIMC.setText("");

        // Volta para a primeira opção (selecionar...)
        if (cbAluno.getItemCount() > 0) {
            cbAluno.setSelectedIndex(0);
        }
        if (cbFuncionario.getItemCount() > 0) {
            cbFuncionario.setSelectedIndex(0);
        }

        txtPeso.requestFocus();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCalcularIMC;
    private javax.swing.JButton btSair;
    private javax.swing.JButton btSalvar;
    private javax.swing.JComboBox<String> cbAluno;
    private javax.swing.JComboBox<String> cbFuncionario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel laData;
    private javax.swing.JLabel lblResultadoIMC;
    private javax.swing.JTextField txtAltura;
    private javax.swing.JTextField txtGordura;
    private javax.swing.JTextArea txtObservacoes;
    private javax.swing.JTextField txtPeso;
    // End of variables declaration//GEN-END:variables
}
