/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package apresentacao;

import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import negocio.Aluno;
import negocio.Exercicio;
import negocio.Funcionario;
import negocio.Treino;
import persistencia.AlunoDAO;
import persistencia.ExercicioDAO;
import persistencia.FuncionarioDAO;
import persistencia.IAlunoDAO;
import persistencia.IExercicioDAO;
import persistencia.IFuncionarioDAO;
import persistencia.ITreinoDAO;
import persistencia.TreinoDAO;

/**
 *
 * @author giuli
 */
public class fmFichaTreino extends javax.swing.JInternalFrame {   
    /**
     * Creates new form fmFichaTreino
     */
    public fmFichaTreino() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbAluno = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        cbFuncionario = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txtVencimento = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        txtInicio = new javax.swing.JFormattedTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cbExercicio = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btAdicionar = new javax.swing.JButton();
        spSeries = new javax.swing.JSpinner();
        spRepeticoes = new javax.swing.JSpinner();
        spCarga = new javax.swing.JSpinner();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbTreino = new javax.swing.JTable();
        btSalvar = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Nova Ficha de Treino");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Aluno", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 153, 153))); // NOI18N

        jLabel1.setText("Aluno");

        cbAluno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAlunoActionPerformed(evt);
            }
        });

        jLabel2.setText("Instrutor");

        cbFuncionario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel7.setText("Data de Inicio");

        try {
            txtVencimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel8.setText("Vencimento");

        try {
            txtInicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cbAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGap(7, 7, 7)
                            .addComponent(cbFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Exercicios", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 153, 153))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(255, 204, 204));

        jLabel3.setText("Exercício");

        cbExercicio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setText("Séries");

        jLabel5.setText("Repetições");

        jLabel6.setText("Carga");

        btAdicionar.setBackground(new java.awt.Color(102, 102, 255));
        btAdicionar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btAdicionar.setForeground(new java.awt.Color(255, 255, 255));
        btAdicionar.setText("Adicionar Exercicio");
        btAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdicionarActionPerformed(evt);
            }
        });

        spSeries.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        spRepeticoes.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        spCarga.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        spCarga.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cbExercicio, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(spSeries)
                            .addComponent(spRepeticoes)
                            .addComponent(spCarga, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btAdicionar)
                        .addGap(19, 19, 19))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbExercicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(spSeries, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(spRepeticoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(btAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(spCarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tbTreino.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tbTreino.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Exercicio", "Séries", "Repetições", "Carga"
            }
        ));
        jScrollPane2.setViewportView(tbTreino);

        btSalvar.setBackground(new java.awt.Color(0, 153, 51));
        btSalvar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btSalvar.setForeground(new java.awt.Color(255, 255, 255));
        btSalvar.setText("Finalizar Ficha");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btSalvar)
                .addGap(178, 178, 178))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btSalvar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        try {
            // Valida aluno
            if (cbAluno.getSelectedIndex() == 0) {
                JOptionPane.showMessageDialog(this, 
                    "Selecione um aluno!", 
                    "Aluno não selecionado", 
                    JOptionPane.WARNING_MESSAGE);
                return;
            }

            // Valida funcionário
            if (cbFuncionario.getSelectedIndex() == 0) {
                JOptionPane.showMessageDialog(this, 
                    "Selecione um instrutor!", 
                    "Instrutor não selecionado", 
                    JOptionPane.WARNING_MESSAGE);
                return;
            }

            // Valida tabela de exercícios
            if (tbTreino.getRowCount() == 0) {
                JOptionPane.showMessageDialog(this, 
                    "Adicione pelo menos um exercício!", 
                    "Tabela vazia", 
                    JOptionPane.WARNING_MESSAGE);
                return;
            }

            // Valida datas
            String dataInicioStr = txtInicio.getText().trim();
            String dataVencimentoStr = txtVencimento.getText().trim();

            // Verifica se datas estão preenchidas corretamente
            if (dataInicioStr.equals("  /  /    ") || dataInicioStr.replace("/", "").trim().length() != 8) {
                JOptionPane.showMessageDialog(this, 
                    "Preencha corretamente a data de início (dd/mm/aaaa)!", 
                    "Data de início inválida", 
                    JOptionPane.WARNING_MESSAGE);
                txtInicio.requestFocus();
                return;
            }

            if (dataVencimentoStr.equals("  /  /    ") || dataVencimentoStr.replace("/", "").trim().length() != 8) {
                JOptionPane.showMessageDialog(this, 
                    "Preencha corretamente a data de vencimento (dd/mm/aaaa)!", 
                    "Data de vencimento inválida", 
                    JOptionPane.WARNING_MESSAGE);
                txtVencimento.requestFocus();
                return;
            }

            // Pega nome do aluno (string do combobox)
            String nomeAluno = (String) cbAluno.getSelectedItem();

            // Pega nome do funcionário (string do combobox)
            String nomeFuncionario = (String) cbFuncionario.getSelectedItem();

            // Converte tabela para string
            String treinoString = converterTabelaParaString();

            // CONVERTE DATAS
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");

            Date dataInicio;
            Date dataFim;

            try {
                dataInicio = sdf.parse(dataInicioStr);
                dataFim = sdf.parse(dataVencimentoStr);

                // Verifica se data fim ta depois
                if (dataFim.before(dataInicio) || dataFim.equals(dataInicio)) {
                    JOptionPane.showMessageDialog(this, 
                        "A data de vencimento deve ser posterior à data de início!", 
                        "Datas inválidas", 
                        JOptionPane.WARNING_MESSAGE);
                    return;
                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, 
                    "Formato de data inválido! Use o formato dd/mm/aaaa\n" +
                    "Exemplo: 15/01/2024", 
                    "Erro de data", 
                    JOptionPane.ERROR_MESSAGE);
                return;
            }

            Treino treino = new Treino();
            treino.setAluno(nomeAluno);
            treino.setFuncionario(nomeFuncionario);
            treino.setTreino(treinoString);
            treino.setDataInicio(dataInicio);
            treino.setDataFim(dataFim);

            ITreinoDAO treinoDAO = new TreinoDAO();
            treinoDAO.adiciona(treino);

            SimpleDateFormat sdfDisplay = new SimpleDateFormat("dd/MM/yyyy");
            String mensagemSucesso = String.format(
                "Ficha de treino salva com sucesso!\n\n" +
                "Aluno: %s\n" +
                "Instrutor: %s\n" +
                "Quantidade de exercícios: %d\n" +
                "Data de início: %s\n" +
                "Data de vencimento: %s\n\n" +
                "Treino salvo:\n%s",
                nomeAluno,
                nomeFuncionario,
                tbTreino.getRowCount(),
                sdfDisplay.format(dataInicio),
                sdfDisplay.format(dataFim),
                formatarTreinoParaExibicao(treinoString)
            );

            JOptionPane.showMessageDialog(this, 
                mensagemSucesso, 
                "Sucesso", 
                JOptionPane.INFORMATION_MESSAGE);

            limparFormulario();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, 
                "Erro ao salvar ficha de treino!\n\n" +
                "Detalhes: " + e.getMessage(), 
                "Erro", 
                JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_btSalvarActionPerformed

    private void cbAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAlunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbAlunoActionPerformed

    private void btAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdicionarActionPerformed
        // 1. Pega valores
        Object exercicio = cbExercicio.getSelectedItem();
        int series = (int) spSeries.getValue();
        int repeticoes = (int) spRepeticoes.getValue();
        int carga = (int) spCarga.getValue(); // ou double se for decimal

        // 2. Validação
        if (series <= 0 || repeticoes <= 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Séries e repetições devem ser maiores que zero!");
            return;
        }

        // 3. Adiciona na Tabela
        DefaultTableModel modelo = (DefaultTableModel) tbTreino.getModel();
        modelo.addRow(new Object[]{ 
            exercicio, 
            String.valueOf(series), 
            String.valueOf(repeticoes), 
            String.valueOf(carga) 
        });

        // 4. Limpa campos
        spSeries.setValue(1); // Valor padrão mínimo
        spRepeticoes.setValue(1);
        spCarga.setValue(0);

        // 5. Foco
        spSeries.requestFocus();
    }//GEN-LAST:event_btAdicionarActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        try {
            // ALUNOS
            IAlunoDAO alunoDAO = new AlunoDAO();
            DefaultComboBoxModel modeloAluno = new DefaultComboBoxModel();

            // Adiciona opção padrão
            modeloAluno.addElement("Aluno...");

            for (Aluno aluno : alunoDAO.listarTodos()) {
                modeloAluno.addElement(aluno.getNome());
            }

            cbAluno.setModel(modeloAluno);
            cbAluno.setSelectedIndex(0);

            IFuncionarioDAO funcionarioDAO = new FuncionarioDAO();
            DefaultComboBoxModel modeloFunc = new DefaultComboBoxModel();

            modeloFunc.addElement("Funcionario...");

            for (Funcionario func : funcionarioDAO.listarTodos()) {
                modeloFunc.addElement(func.getNome());
            }

            cbFuncionario.setModel(modeloFunc);
            cbFuncionario.setSelectedIndex(0);
            
            IExercicioDAO exercicioDAO = new ExercicioDAO();
            DefaultComboBoxModel modeloExercicio = new DefaultComboBoxModel();

            // Adiciona opção padrão
            modeloExercicio.addElement("Exercicio...");

            for (Exercicio exercicio : exercicioDAO.listarTodos()) {
                modeloExercicio.addElement(exercicio.getNome());
            }
            
            cbExercicio.setModel(modeloExercicio);
            cbExercicio.setSelectedIndex(0);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, 
                "Erro ao carregar dados: " + e.getMessage(), 
                "Erro", 
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_formInternalFrameOpened

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        // TODO add your handling code here:
        try {
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            Date hoje = new Date();

            // Data de início = hoje
            txtInicio.setText(sdf.format(hoje));

            // Data de vencimento = hoje + 30 dias
            Calendar calendar = Calendar.getInstance();
            calendar.setTime(hoje);
            calendar.add(Calendar.DAY_OF_MONTH, 30);
            txtVencimento.setText(sdf.format(calendar.getTime()));

        } catch (Exception e) {
            // Ignora erro, mantém campos vazios
        }
    }//GEN-LAST:event_formInternalFrameActivated

    private String formatarTreinoParaExibicao(String treinoString) {
        if (treinoString == null || treinoString.isEmpty()) {
            return "Nenhum exercício";
        }

        StringBuilder sb = new StringBuilder();
        String[] linhas = treinoString.split(";");

        for (int i = 0; i < linhas.length; i++) {
            String[] colunas = linhas[i].split(",");
            if (colunas.length >= 4) {
                sb.append(String.format("%d. %s: %s séries x %s repetições (%s kg)\n", 
                    i + 1,
                    colunas[0],  // Exercício
                    colunas[1],  // Séries
                    colunas[2],  // Repetições
                    colunas[3]   // Carga
                ));
            }
        }

        return sb.toString();
    }
    
    private String converterTabelaParaString() {
        StringBuilder sb = new StringBuilder();
        int linhas = tbTreino.getRowCount();
        int colunas = tbTreino.getColumnCount();

        for (int linha = 0; linha < linhas; linha++) {
            for (int coluna = 0; coluna < colunas; coluna++) {
                Object valor = tbTreino.getValueAt(linha, coluna);
                String texto = (valor != null) ? valor.toString().trim() : "";

                // tira aspas
                texto = texto.replace("\"", "");

                // Se o texto contém vírgula ou ponto e vírgula, coloca entre aspas
                if (texto.contains(",") || texto.contains(";")) {
                    texto = "\"" + texto + "\"";
                }

                sb.append(texto);

                if (coluna < colunas - 1) {
                    sb.append(",");
                }
            }
            if (linha < linhas - 1) {
                sb.append(";");
            }
        }

        return sb.toString();
    }

    // MÉTODO PARA LIMPAR FORMULÁRIO
    private void limparFormulario() {
        cbAluno.setSelectedIndex(0);
        cbFuncionario.setSelectedIndex(0);
        cbExercicio.setSelectedIndex(0);

        txtInicio.setText("");
        txtVencimento.setText("");

        DefaultTableModel modelo = (DefaultTableModel) tbTreino.getModel();
        modelo.setRowCount(0);

        spSeries.setValue(3);
        spRepeticoes.setValue(10);
        spCarga.setValue(10);

        cbAluno.requestFocus();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdicionar;
    private javax.swing.JButton btSalvar;
    private javax.swing.JComboBox<String> cbAluno;
    private javax.swing.JComboBox<String> cbExercicio;
    private javax.swing.JComboBox<String> cbFuncionario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JSpinner spCarga;
    private javax.swing.JSpinner spRepeticoes;
    private javax.swing.JSpinner spSeries;
    private javax.swing.JTable tbTreino;
    private javax.swing.JFormattedTextField txtInicio;
    private javax.swing.JFormattedTextField txtVencimento;
    // End of variables declaration//GEN-END:variables
}
