/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package apresentacao;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import negocio.Aluno;
import persistencia.AlunoDAO;
import persistencia.IAlunoDAO;

/**
 *
 * @author giuli
 */
public class fmListagem extends javax.swing.JInternalFrame {

    /**
     * Creates new form fmListagem
     */
    public fmListagem() {
        initComponents();
        carregarTodosAlunos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtAlunos = new javax.swing.JTable();
        btExcluir = new javax.swing.JButton();
        txtBuscaNome = new javax.swing.JTextField();
        btBuscar = new javax.swing.JButton();

        setClosable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setText("Buscar Aluno");

        jtAlunos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nome", "CPF", "Telefone", "Plano"
            }
        ));
        jScrollPane1.setViewportView(jtAlunos);

        btExcluir.setBackground(new java.awt.Color(102, 102, 255));
        btExcluir.setForeground(new java.awt.Color(255, 255, 255));
        btExcluir.setText("Excluir Aluno");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        btBuscar.setText("Buscar");
        btBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBuscaNome, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btBuscar))
                    .addComponent(btExcluir)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtBuscaNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btExcluir)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        int linhaSelecionada = jtAlunos.getSelectedRow();
        
        if (linhaSelecionada == -1) {
            JOptionPane.showMessageDialog(this, 
                "Selecione um aluno para excluir.", 
                "Aviso", 
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        DefaultTableModel model = (DefaultTableModel) jtAlunos.getModel();
        int idAluno = Integer.parseInt(model.getValueAt(linhaSelecionada, 0).toString());
        String nomeAluno = model.getValueAt(linhaSelecionada, 1).toString();
        
        int confirmacao = JOptionPane.showConfirmDialog(this,
            "Tem certeza que deseja excluir o aluno:\n" + nomeAluno + "?",
            "Confirmar Exclusão",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE);
        
        if (confirmacao == JOptionPane.YES_OPTION) {
            try {
                IAlunoDAO dao = new AlunoDAO();
                dao.remove(idAluno);
                
                JOptionPane.showMessageDialog(this,
                    "Aluno excluído com sucesso!",
                    "Sucesso",
                    JOptionPane.INFORMATION_MESSAGE);
                
                carregarTodosAlunos();
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this,
                    "Erro ao excluir aluno: " + e.getMessage(),
                    "Erro",
                    JOptionPane.ERROR_MESSAGE);
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btExcluirActionPerformed

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        // TODO add your handling code here:
        if (txtBuscaNome.getText().trim().isEmpty()) {
            carregarTodosAlunos();
        }
    }//GEN-LAST:event_formInternalFrameActivated

    private void btBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarActionPerformed
        // TODO add your handling code here:
        realizarBusca();
    }//GEN-LAST:event_btBuscarActionPerformed
    private void carregarTodosAlunos() {
        System.out.println("DEBUG: Carregando todos os alunos...");
        
        try {
            IAlunoDAO dao = new AlunoDAO();
            List<Aluno> alunos = dao.listarTodos();
            
            System.out.println("DEBUG: " + alunos.size() + " alunos encontrados");
            
            atualizarTabela(alunos);
            
        } catch (Exception e) {
            System.err.println("ERRO ao carregar alunos: " + e.getMessage());
            e.printStackTrace();
            
            JOptionPane.showMessageDialog(this,
                "Erro ao carregar alunos:\n" + e.getMessage(),
                "Erro",
                JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void atualizarTabela(List<Aluno> alunos) {
        System.out.println("DEBUG: Atualizando tabela com " + alunos.size() + " alunos");
        

        DefaultTableModel model = new DefaultTableModel();

        model.addColumn("ID");
        model.addColumn("Nome");
        model.addColumn("CPF");
        model.addColumn("Telefone");
        model.addColumn("Plano");
        model.addColumn("Status");
        

        for (Aluno aluno : alunos) {
            String status = aluno.isAtivo() ? "Ativo" : "Inativo";
            model.addRow(new Object[]{
                aluno.getIdAluno(),
                aluno.getNome(),
                aluno.getCpf(),
                aluno.getTelefone(),
                aluno.getPlano(),
                status
            });
        }

        jtAlunos.setModel(model);
        
        System.out.println("DEBUG: Modelo aplicado. " + model.getRowCount() + " linhas na tabela");
        

        ajustarLarguraColunas();
    }

    private void realizarBusca() {
        String nome = txtBuscaNome.getText().trim();
        
        if (nome.isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "Digite um nome para buscar.", 
                "Aviso", 
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        System.out.println("DEBUG: Buscando por: " + nome);
        
        try {
            IAlunoDAO dao = new AlunoDAO();
            List<Aluno> alunos = dao.listarPorNome(nome);
            
            if (alunos.isEmpty()) {
                JOptionPane.showMessageDialog(this, 
                    "Nenhum aluno encontrado com: " + nome, 
                    "Busca", 
                    JOptionPane.INFORMATION_MESSAGE);
            } else {
                System.out.println("DEBUG: " + alunos.size() + " alunos encontrados na busca");
                atualizarTabela(alunos);
            }
            
        } catch (Exception e) {
            System.err.println("ERRO na busca: " + e.getMessage());
            e.printStackTrace();
            
            JOptionPane.showMessageDialog(this,
                "Erro na busca: " + e.getMessage(),
                "Erro",
                JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void ajustarLarguraColunas() {
        if (jtAlunos.getColumnCount() > 0) {
            jtAlunos.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
            
            // Ajustar cada coluna
            jtAlunos.getColumnModel().getColumn(0).setPreferredWidth(40);   // ID
            jtAlunos.getColumnModel().getColumn(1).setPreferredWidth(200);  // Nome
            jtAlunos.getColumnModel().getColumn(2).setPreferredWidth(130);  // CPF
            jtAlunos.getColumnModel().getColumn(3).setPreferredWidth(120);  // Telefone
            jtAlunos.getColumnModel().getColumn(4).setPreferredWidth(80);   // Plano
            jtAlunos.getColumnModel().getColumn(5).setPreferredWidth(60);   // Status
            
            System.out.println("DEBUG: Colunas ajustadas: " + jtAlunos.getColumnCount() + " colunas");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBuscar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtAlunos;
    private javax.swing.JTextField txtBuscaNome;
    // End of variables declaration//GEN-END:variables
}
