/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package apresentacao;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author giuli
 */
public class fmListagem extends javax.swing.JInternalFrame {

    /**
     * Creates new form fmListagem
     */
    public fmListagem() {
        initComponents();
        // Configura o modelo da tabela
    DefaultTableModel modelo = (DefaultTableModel) tbAlunos.getModel();
    
    // Adiciona linhas falsas para testar
    modelo.addRow(new Object[]{"Ana Clara", "123.456.789-00", "(11) 99999-0000", "Mensal"});
    modelo.addRow(new Object[]{"Bruno Souza", "111.222.333-44", "(21) 98888-1111", "Anual"});
    modelo.addRow(new Object[]{"Carlos Lima", "555.666.777-88", "(31) 97777-2222", "Trimestral"});
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtBusca = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbAlunos = new javax.swing.JTable();
        btExcluir = new javax.swing.JButton();

        jLabel1.setText("Buscar Aluno");

        txtBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscaActionPerformed(evt);
            }
        });
        txtBusca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscaKeyReleased(evt);
            }
        });

        tbAlunos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nome", "CPF", "Telefone", "Plano"
            }
        ));
        jScrollPane1.setViewportView(tbAlunos);

        btExcluir.setText("Excluir Aluno");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btExcluir)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btExcluir)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscaActionPerformed

    private void txtBuscaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscaKeyReleased
        // 1. Pega o que foi digitado
    String chave = txtBusca.getText().toLowerCase();
    
    // 2. Pega o modelo da tabela para mexer nele
    DefaultTableModel modelo = (DefaultTableModel) tbAlunos.getModel();
    modelo.setNumRows(0); // Limpa a tabela toda
    
    // 3. Recria os dados falsos (Simulando o Banco de Dados)
    // O seu amigo fará isso vir do SQL depois
    String[][] dadosFake = {
        {"Ana Clara", "123.456.789-00", "(11) 99999-0000", "Mensal"},
        {"Bruno Souza", "111.222.333-44", "(21) 98888-1111", "Anual"},
        {"Carlos Lima", "555.666.777-88", "(31) 97777-2222", "Trimestral"}
    };
    
    // 4. Adiciona de volta SÓ o que combina com o texto
    for (String[] aluno : dadosFake) {
        // Se o nome (posição 0) contém o que foi digitado...
        if (aluno[0].toLowerCase().contains(chave)) {
            modelo.addRow(aluno);
        }
    }
    }//GEN-LAST:event_txtBuscaKeyReleased

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        // 1. Verifica se tem alguma linha selecionada na tabela
    int linhaSelecionada = tbAlunos.getSelectedRow();
    
    if (linhaSelecionada == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Selecione um aluno na tabela para excluir!");
        return;
    }

    // 2. Confirmação (Segurança)
    int opcao = javax.swing.JOptionPane.showConfirmDialog(this, "Tem certeza que deseja excluir?", "Atenção", javax.swing.JOptionPane.YES_NO_OPTION);
    
    if (opcao == javax.swing.JOptionPane.YES_OPTION) {
        // 3. Remove a linha da tabela (Visualmente)
        // Obs: Seu amigo do banco vai colocar o código SQL aqui depois
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tbAlunos.getModel();
        modelo.removeRow(linhaSelecionada);
        
        javax.swing.JOptionPane.showMessageDialog(this, "Aluno removido com sucesso!");
    }
    }//GEN-LAST:event_btExcluirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btExcluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbAlunos;
    private javax.swing.JTextField txtBusca;
    // End of variables declaration//GEN-END:variables
}
