/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package apresentacao;
import com.formdev.flatlaf.FlatDarkLaf; // Import do tema escuro
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.beans.PropertyVetoException;
import javax.swing.JInternalFrame;
import javax.swing.Timer;

/**
 *
 * @author giuli
 */
public class fmPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(fmPrincipal.class.getName());

    /**
     * Creates new form fmPrincipal
     */
    public fmPrincipal() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        laDataHora = new javax.swing.JLabel();
        lacalendario = new javax.swing.JLabel();
        laJavaGym = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btAddAluno = new javax.swing.JButton();
        btTreino = new javax.swing.JButton();
        btPagamentos = new javax.swing.JButton();
        btLista1 = new javax.swing.JButton();
        btFuncionario = new javax.swing.JButton();
        btInfo = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btSair = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        itCadrastros = new javax.swing.JMenu();
        itAlunos = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        itProcessos = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        itFichas = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        itListagem = new javax.swing.JMenuItem();
        itAjuda = new javax.swing.JMenu();
        itSobre = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar2.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar2.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JavaGym");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jDesktopPane1.setBackground(new java.awt.Color(56, 61, 69));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        laDataHora.setText("             ");

        lacalendario.setText("<html>📅</html>");

        laJavaGym.setText("️JavaGym  0.1.2v - Sistema de Gestão️ ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(laJavaGym)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lacalendario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(laDataHora)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(laDataHora)
                    .addComponent(lacalendario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(laJavaGym))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(56, 61, 69));

        btAddAluno.setBackground(new java.awt.Color(62, 67, 76));
        btAddAluno.setFont(new java.awt.Font("Gadugi", 0, 12)); // NOI18N
        btAddAluno.setForeground(new java.awt.Color(255, 255, 255));
        btAddAluno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/icons_news/addpessoa.png"))); // NOI18N
        btAddAluno.setText("<html><b>ALUNOS</b><br>Cadastre novos alunos</html>");
        btAddAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddAlunoActionPerformed(evt);
            }
        });

        btTreino.setBackground(new java.awt.Color(62, 67, 76));
        btTreino.setFont(new java.awt.Font("Gadugi", 0, 12)); // NOI18N
        btTreino.setForeground(new java.awt.Color(255, 255, 255));
        btTreino.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/icons_news/addtreino.png"))); // NOI18N
        btTreino.setText("<html><b>TREINOS</b><br>Crie novos treinos</html>");
        btTreino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTreinoActionPerformed(evt);
            }
        });

        btPagamentos.setBackground(new java.awt.Color(62, 67, 76));
        btPagamentos.setFont(new java.awt.Font("Gadugi", 0, 12)); // NOI18N
        btPagamentos.setForeground(new java.awt.Color(255, 255, 255));
        btPagamentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/icons_news/pagamento.png"))); // NOI18N
        btPagamentos.setText("<html><b>PAGAMENTOS</b><br>Controle de pagamentos</html>");
        btPagamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPagamentosActionPerformed(evt);
            }
        });

        btLista1.setBackground(new java.awt.Color(62, 67, 76));
        btLista1.setFont(new java.awt.Font("Gadugi", 0, 12)); // NOI18N
        btLista1.setForeground(new java.awt.Color(255, 255, 255));
        btLista1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/icons_news/listaalunos.png"))); // NOI18N
        btLista1.setText("<html><b>LISTAGEM</b><br>Consulte e gerencie alunos</html>");
        btLista1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLista1ActionPerformed(evt);
            }
        });

        btFuncionario.setBackground(new java.awt.Color(62, 67, 76));
        btFuncionario.setFont(new java.awt.Font("Gadugi", 0, 12)); // NOI18N
        btFuncionario.setForeground(new java.awt.Color(255, 255, 255));
        btFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/icons_news/addfunc.png"))); // NOI18N
        btFuncionario.setText("<html><b>FUNCIONÁRIOS</b><br>Cadastre novos funcionários</html>");
        btFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFuncionarioActionPerformed(evt);
            }
        });

        btInfo.setBackground(new java.awt.Color(62, 67, 76));
        btInfo.setFont(new java.awt.Font("Gadugi", 0, 12)); // NOI18N
        btInfo.setForeground(new java.awt.Color(255, 255, 255));
        btInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/icons_news/info.png"))); // NOI18N
        btInfo.setText("<html><b>SOBRE</b><br>Informações sobre o sistema</html>");
        btInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInfoActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(0, 153, 51));
        jLabel2.setFont(new java.awt.Font("Gadugi", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Sistema de Gestão Para Academias");

        jLabel1.setFont(new java.awt.Font("Gadugi", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 255));
        jLabel1.setText("<html>• Força • Disciplina • Evolução •</html>");

        jLabel3.setBackground(new java.awt.Color(0, 153, 51));
        jLabel3.setFont(new java.awt.Font("Gadugi", 1, 44)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Bem-vindo ao JavaGym!");

        btSair.setBackground(new java.awt.Color(102, 102, 255));
        btSair.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel1))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(btTreino, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btAddAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(btPagamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btLista1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(350, 350, 350)
                .addComponent(btSair, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(45, 45, 45)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btTreino, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btAddAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btPagamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btLista1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(btSair))
        );

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/icons_news/logo_extendida2.png"))); // NOI18N

        jDesktopPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        itCadrastros.setText("Cadastros");

        itAlunos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itAlunos.setText("Aluno");
        itAlunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itAlunosActionPerformed(evt);
            }
        });
        itCadrastros.add(itAlunos);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem1.setText("Funcionário");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        itCadrastros.add(jMenuItem1);

        jMenuBar1.add(itCadrastros);

        itProcessos.setText("Processos");

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem2.setText("Pagamento");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        itProcessos.add(jMenuItem2);

        itFichas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itFichas.setText("Ficha de Treino");
        itFichas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itFichasActionPerformed(evt);
            }
        });
        itProcessos.add(itFichas);

        jMenuBar1.add(itProcessos);

        jMenu3.setText("Lista");

        itListagem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itListagem.setText("Listar Alunos");
        itListagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itListagemActionPerformed(evt);
            }
        });
        jMenu3.add(itListagem);

        jMenuBar1.add(jMenu3);

        itAjuda.setText("Ajuda");

        itSobre.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itSobre.setText("Sobre");
        itSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itSobreActionPerformed(evt);
            }
        });
        itAjuda.add(itSobre);

        jMenuBar1.add(itAjuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itAlunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itAlunosActionPerformed
        //garante que não vai abrir caso o fm esteja aberto
        for (JInternalFrame frame : jDesktopPane1.getAllFrames()) {
            if (frame instanceof fmAluno && frame.isVisible()) {
                try {
                    frame.setSelected(true);
                    return; // Já está aberta, sai do método
                } catch (PropertyVetoException ex) {
                    ex.printStackTrace();
                }
            }
        }
        fmAluno janela = new fmAluno();
        jDesktopPane1.add(janela);
        janela.setVisible(true);
    }//GEN-LAST:event_itAlunosActionPerformed

    private void itListagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itListagemActionPerformed
       //garante que não vai abrir caso o fm esteja aberto
        for (JInternalFrame frame : jDesktopPane1.getAllFrames()) {
            if (frame instanceof fmListagem && frame.isVisible()) {
                try {
                    frame.setSelected(true);
                    return;
                } catch (PropertyVetoException ex) {
                    ex.printStackTrace();
                }
            }
        }
       
       fmListagem janela = new fmListagem();
       jDesktopPane1.add(janela);
       janela.setVisible(true);
    }//GEN-LAST:event_itListagemActionPerformed

    private void itFichasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itFichasActionPerformed
        //garante que não vai abrir caso o jif esteja aberto
        for (JInternalFrame frame : jDesktopPane1.getAllFrames()) {
            if (frame instanceof fmFichaTreino && frame.isVisible()) {
                try {
                    frame.setSelected(true);
                    return; // Já está aberta, sai do método
                } catch (PropertyVetoException ex) {
                    ex.printStackTrace();
                }
            }
       }
        // Cria a janela de ficha
        fmFichaTreino janela = new fmFichaTreino();

        // Adiciona no painel principal
        jDesktopPane1.add(janela);

        // Faz aparecer
        janela.setVisible(true);
    }//GEN-LAST:event_itFichasActionPerformed
    private String dataHora(){
        DateFormat datahora = new SimpleDateFormat("dd/MM/yy HH:mm:ss");
        
        Date data = new Date();
        return datahora.format(data);
    }
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        laDataHora.setText(dataHora());
        
        ActionListener updater = new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent event){
                laDataHora.setText(dataHora());
            }
        };
        Timer timer = new Timer(1000,updater);
        timer.start();
    }//GEN-LAST:event_formWindowOpened

    private void itSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itSobreActionPerformed
        // TODO add your handling code here:
        fmSobre sobre = new fmSobre();
        jDesktopPane1.add(sobre);
        sobre.setVisible(true);
    }//GEN-LAST:event_itSobreActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        for (JInternalFrame frame : jDesktopPane1.getAllFrames()) {
            if (frame instanceof fmFuncionario && frame.isVisible()) {
                try {
                    frame.setSelected(true);
                    return; 
                } catch (PropertyVetoException ex) {
                    ex.printStackTrace();
                }
            }
        }
        fmFuncionario janela = new fmFuncionario();
        jDesktopPane1.add(janela);
        janela.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        for (JInternalFrame frame : jDesktopPane1.getAllFrames()) {
            if (frame instanceof fmPagamento && frame.isVisible()) {
                try {
                    frame.setSelected(true);
                    return; // Já está aberta, sai do método
                } catch (PropertyVetoException ex) {
                    ex.printStackTrace();
                }
            }
        }
        fmPagamento janela = new fmPagamento();
        jDesktopPane1.add(janela);
        janela.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        // TODO add your handling code here:
        int valor = JOptionPane.showConfirmDialog(
            null,
            "Deseja realmente sair?",              // Mensagem
            "Confirmação",                         // Título da janela
            JOptionPane.YES_NO_OPTION,             // Tipo de opções (Sim/Não)
            JOptionPane.QUESTION_MESSAGE           // Ícone de interrogação
        );

        if (valor == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btSairActionPerformed

    private void btInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInfoActionPerformed
        for (JInternalFrame frame : jDesktopPane1.getAllFrames()) {
            if (frame instanceof fmSobre && frame.isVisible()) {
                try {
                    frame.setSelected(true);
                    return;
                } catch (PropertyVetoException ex) {
                    ex.printStackTrace();
                }
            }
        }
        fmSobre sobre = new fmSobre();
        jDesktopPane1.add(sobre);
        sobre.setVisible(true);
    }//GEN-LAST:event_btInfoActionPerformed

    private void btFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFuncionarioActionPerformed
        for (JInternalFrame frame : jDesktopPane1.getAllFrames()) {
            if (frame instanceof fmFuncionario && frame.isVisible()) {
                try {
                    frame.setSelected(true);
                    return;
                } catch (PropertyVetoException ex) {
                    ex.printStackTrace();
                }
            }
        }
        fmFuncionario janela = new fmFuncionario();
        jDesktopPane1.add(janela);
        janela.setVisible(true);
    }//GEN-LAST:event_btFuncionarioActionPerformed

    private void btLista1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLista1ActionPerformed
        for (JInternalFrame frame : jDesktopPane1.getAllFrames()) {
            if (frame instanceof fmListagem && frame.isVisible()) {
                try {
                    frame.setSelected(true);
                    return;
                } catch (PropertyVetoException ex) {
                    ex.printStackTrace();
                }
            }
        }

        fmListagem janela = new fmListagem();
        jDesktopPane1.add(janela);
        janela.setVisible(true);
    }//GEN-LAST:event_btLista1ActionPerformed

    private void btPagamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPagamentosActionPerformed
        for (JInternalFrame frame : jDesktopPane1.getAllFrames()) {
            if (frame instanceof fmPagamento && frame.isVisible()) {
                try {
                    frame.setSelected(true);
                    return; // Já está aberta, sai do método
                } catch (PropertyVetoException ex) {
                    ex.printStackTrace();
                }
            }
        }
        fmPagamento janela = new fmPagamento();
        jDesktopPane1.add(janela);
        janela.setVisible(true);
    }//GEN-LAST:event_btPagamentosActionPerformed

    private void btTreinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTreinoActionPerformed
        // TODO add your handling code here:
        for (JInternalFrame frame : jDesktopPane1.getAllFrames()) {
            if (frame instanceof fmFichaTreino && frame.isVisible()) {
                try {
                    frame.setSelected(true);
                    return;
                } catch (PropertyVetoException ex) {
                    ex.printStackTrace();
                }
            }
        }

        fmFichaTreino janela = new fmFichaTreino();
        jDesktopPane1.add(janela);
        janela.setVisible(true);
    }//GEN-LAST:event_btTreinoActionPerformed

    private void btAddAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddAlunoActionPerformed
        // TODO add your handling code here:

        //garante que não vai abrir caso o jif esteja aberto
        for (JInternalFrame frame : jDesktopPane1.getAllFrames()) {
            if (frame instanceof fmAluno && frame.isVisible()) {
                try {
                    frame.setSelected(true);
                    return;
                } catch (PropertyVetoException ex) {
                    ex.printStackTrace();
                }
            }
        }

        fmAluno janela = new fmAluno();
        jDesktopPane1.add(janela);
        janela.setVisible(true);
    }//GEN-LAST:event_btAddAlunoActionPerformed
    
    /**
     * @param args the command line arguments
     */
   public static void main(String args[]) {
        try {
            
            javax.swing.UIManager.setLookAndFeel( new com.formdev.flatlaf.FlatDarkLaf() );
        } catch( Exception ex ) {
            System.err.println( "Erro no tema. Usando padrão." );
        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAddAluno;
    private javax.swing.JButton btFuncionario;
    private javax.swing.JButton btInfo;
    private javax.swing.JButton btLista1;
    private javax.swing.JButton btPagamentos;
    private javax.swing.JButton btSair;
    private javax.swing.JButton btTreino;
    private javax.swing.JMenu itAjuda;
    private javax.swing.JMenuItem itAlunos;
    private javax.swing.JMenu itCadrastros;
    private javax.swing.JMenuItem itFichas;
    private javax.swing.JMenuItem itListagem;
    private javax.swing.JMenu itProcessos;
    private javax.swing.JMenuItem itSobre;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel laDataHora;
    private javax.swing.JLabel laJavaGym;
    private javax.swing.JLabel lacalendario;
    // End of variables declaration//GEN-END:variables
}
