/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package apresentacao;
import com.formdev.flatlaf.FlatDarkLaf; // Import do tema escuro
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.beans.PropertyVetoException;
import javax.swing.JInternalFrame;
import javax.swing.Timer;

/**
 *
 * @author giuli
 */
public class fmPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(fmPrincipal.class.getName());

    /**
     * Creates new form fmPrincipal
     */
    public fmPrincipal() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        laDataHora = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btAddAluno = new javax.swing.JButton();
        btSair = new javax.swing.JButton();
        btLista = new javax.swing.JButton();
        jtPagamentos = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        itCadrastros = new javax.swing.JMenu();
        itAlunos = new javax.swing.JMenuItem();
        itListagem = new javax.swing.JMenuItem();
        itProcessos = new javax.swing.JMenu();
        itAvaliacao = new javax.swing.JMenuItem();
        itFichas = new javax.swing.JMenuItem();
        itAjuda = new javax.swing.JMenu();
        itSobre = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar2.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar2.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JavaGym");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        laDataHora.setText("             ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(laDataHora)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(laDataHora)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        btAddAluno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/addaluno.png"))); // NOI18N
        btAddAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddAlunoActionPerformed(evt);
            }
        });

        btSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/sair.png"))); // NOI18N
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        btLista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/lista.png"))); // NOI18N
        btLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btListaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btLista)
                    .addComponent(btSair)
                    .addComponent(btAddAluno))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(btAddAluno)
                .addGap(18, 18, 18)
                .addComponent(btLista)
                .addGap(18, 18, 18)
                .addComponent(btSair)
                .addGap(18, 18, 18))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id", "Nome", "Status"
            }
        ));
        jtPagamentos.setViewportView(jTable1);

        jDesktopPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jtPagamentos, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addComponent(jtPagamentos, javax.swing.GroupLayout.DEFAULT_SIZE, 421, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtPagamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(0, 90, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        itCadrastros.setText("Cadastros");

        itAlunos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itAlunos.setText("Alunos");
        itAlunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itAlunosActionPerformed(evt);
            }
        });
        itCadrastros.add(itAlunos);

        itListagem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itListagem.setText("Listar Alunos");
        itListagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itListagemActionPerformed(evt);
            }
        });
        itCadrastros.add(itListagem);

        jMenuBar1.add(itCadrastros);

        itProcessos.setText("Processos");

        itAvaliacao.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itAvaliacao.setText("Avaliação Física");
        itAvaliacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itAvaliacaoActionPerformed(evt);
            }
        });
        itProcessos.add(itAvaliacao);

        itFichas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itFichas.setText("Ficha de Treino");
        itFichas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itFichasActionPerformed(evt);
            }
        });
        itProcessos.add(itFichas);

        jMenuBar1.add(itProcessos);

        itAjuda.setText("Ajuda");

        itSobre.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itSobre.setText("Sobre");
        itSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itSobreActionPerformed(evt);
            }
        });
        itAjuda.add(itSobre);

        jMenuBar1.add(itAjuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itAlunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itAlunosActionPerformed
        //garante que não vai abrir caso o fm esteja aberto
        for (JInternalFrame frame : jDesktopPane1.getAllFrames()) {
            if (frame instanceof fmAluno && frame.isVisible()) {
                try {
                    frame.setSelected(true);
                    return; // Já está aberta, sai do método
                } catch (PropertyVetoException ex) {
                    ex.printStackTrace();
                }
            }
        }
        fmAluno janela = new fmAluno();
        jDesktopPane1.add(janela);
        janela.setVisible(true);
    }//GEN-LAST:event_itAlunosActionPerformed

    private void itListagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itListagemActionPerformed
       //garante que não vai abrir caso o fm esteja aberto
        for (JInternalFrame frame : jDesktopPane1.getAllFrames()) {
            if (frame instanceof fmListagem && frame.isVisible()) {
                try {
                    frame.setSelected(true);
                    return; // Já está aberta, sai do método
                } catch (PropertyVetoException ex) {
                    ex.printStackTrace();
                }
            }
        }
       
       fmListagem janela = new fmListagem();
       jDesktopPane1.add(janela);
       janela.setVisible(true);
    }//GEN-LAST:event_itListagemActionPerformed

    private void itAvaliacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itAvaliacaoActionPerformed
       //garante que não vai abrir caso o fm esteja aberto
        for (JInternalFrame frame : jDesktopPane1.getAllFrames()) {
            if (frame instanceof fmAvaliacao && frame.isVisible()) {
                try {
                    frame.setSelected(true);
                    return; // Já está aberta, sai do método
                } catch (PropertyVetoException ex) {
                    ex.printStackTrace();
                }
            }
       }
       fmAvaliacao janela = new fmAvaliacao();
       jDesktopPane1.add(janela);
       janela.setVisible(true);
    }//GEN-LAST:event_itAvaliacaoActionPerformed

    private void itFichasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itFichasActionPerformed
        //garante que não vai abrir caso o jif esteja aberto
        for (JInternalFrame frame : jDesktopPane1.getAllFrames()) {
            if (frame instanceof fmFichaTreino && frame.isVisible()) {
                try {
                    frame.setSelected(true);
                    return; // Já está aberta, sai do método
                } catch (PropertyVetoException ex) {
                    ex.printStackTrace();
                }
            }
       }
        // Cria a janela de ficha
        fmFichaTreino janela = new fmFichaTreino();

        // Adiciona no painel principal
        jDesktopPane1.add(janela);

        // Faz aparecer
        janela.setVisible(true);
    }//GEN-LAST:event_itFichasActionPerformed
    private String dataHora(){
        DateFormat datahora = new SimpleDateFormat("dd/MM/yy HH:mm:ss");
        
        Date data = new Date();
        return datahora.format(data);
    }
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        laDataHora.setText(dataHora());
        
        ActionListener updater = new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent event){
                laDataHora.setText(dataHora());
            }
        };
        Timer timer = new Timer(1000,updater);
        timer.start();
    }//GEN-LAST:event_formWindowOpened

    private void itSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itSobreActionPerformed
        // TODO add your handling code here:
        fmSobre sobre = new fmSobre();
        jDesktopPane1.add(sobre);
        sobre.setVisible(true);
    }//GEN-LAST:event_itSobreActionPerformed

    private void btListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btListaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btListaActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        // TODO add your handling code here:
        int valor = JOptionPane.showConfirmDialog(
            null,
            "Deseja realmente sair?",              // Mensagem
            "Confirmação",                         // Título da janela
            JOptionPane.YES_NO_OPTION,             // Tipo de opções (Sim/Não)
            JOptionPane.QUESTION_MESSAGE           // Ícone de interrogação
        );

        if (valor == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btSairActionPerformed

    private void btAddAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddAlunoActionPerformed
        // TODO add your handling code here:

        //garante que não vai abrir caso o jif esteja aberto
        for (JInternalFrame frame : jDesktopPane1.getAllFrames()) {
            if (frame instanceof fmAluno && frame.isVisible()) {
                try {
                    frame.setSelected(true);
                    return; // Já está aberta, sai do método
                } catch (PropertyVetoException ex) {
                    ex.printStackTrace();
                }
            }
        }

        fmAluno janela = new fmAluno();
        jDesktopPane1.add(janela);
        janela.setVisible(true);
    }//GEN-LAST:event_btAddAlunoActionPerformed
    
    /**
     * @param args the command line arguments
     */
   public static void main(String args[]) {
        try {
            
            javax.swing.UIManager.setLookAndFeel( new com.formdev.flatlaf.FlatDarkLaf() );
        } catch( Exception ex ) {
            System.err.println( "Erro no tema. Usando padrão." );
        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAddAluno;
    private javax.swing.JButton btLista;
    private javax.swing.JButton btSair;
    private javax.swing.JMenu itAjuda;
    private javax.swing.JMenuItem itAlunos;
    private javax.swing.JMenuItem itAvaliacao;
    private javax.swing.JMenu itCadrastros;
    private javax.swing.JMenuItem itFichas;
    private javax.swing.JMenuItem itListagem;
    private javax.swing.JMenu itProcessos;
    private javax.swing.JMenuItem itSobre;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTable jTable1;
    private javax.swing.JScrollPane jtPagamentos;
    private javax.swing.JLabel laDataHora;
    // End of variables declaration//GEN-END:variables
}
